#ifndef RTVAL_PROCS_H
#define RTVAL_PROCS_H

#define RT_NO_API_WRAPPERS
#include "rt_ext_compute.h"
#include "rt_ext_glfw.h"
#include "rt_ext_swapchain.h"
#include "rutile.h"
#include "types.h"
#undef RT_NO_API_WRAPPERS

extern PFN_rtInit rtval_next_rtInit;
extern PFN_rtExit rtval_next_rtExit;
extern PFN_rtError rtval_next_rtError;
extern PFN_rtErrorMessage rtval_next_rtErrorMessage;
extern PFN_rtClearError rtval_next_rtClearError;
extern PFN_rtGetName rtval_next_rtGetName;
extern PFN_rtQueryFormatCapabilities rtval_next_rtQueryFormatCapabilities;
extern PFN_rtBufferCreate rtval_next_rtBufferCreate;
extern PFN_rtBufferDestroy rtval_next_rtBufferDestroy;
extern PFN_rtBufferData rtval_next_rtBufferData;
extern PFN_rtBufferSubdata rtval_next_rtBufferSubdata;
extern PFN_rtBufferRead rtval_next_rtBufferRead;
extern PFN_rtBufferMap rtval_next_rtBufferMap;
extern PFN_rtBufferUnmap rtval_next_rtBufferUnmap;
extern PFN_rtTextureCreate rtval_next_rtTextureCreate;
extern PFN_rtTextureDestroy rtval_next_rtTextureDestroy;
extern PFN_rtTextureViewCreate rtval_next_rtTextureViewCreate;
extern PFN_rtTextureViewDestroy rtval_next_rtTextureViewDestroy;
extern PFN_rtTextureViewFilter rtval_next_rtTextureViewFilter;
extern PFN_rtTextureViewAddress rtval_next_rtTextureViewAddress;
extern PFN_rtTextureViewAnisotropy rtval_next_rtTextureViewAnisotropy;
extern PFN_rtTextureViewLod rtval_next_rtTextureViewLod;
extern PFN_rtTextureCopy rtval_next_rtTextureCopy;
extern PFN_rtTextureData rtval_next_rtTextureData;
extern PFN_rtTextureSubcopy rtval_next_rtTextureSubcopy;
extern PFN_rtTextureSubdata rtval_next_rtTextureSubdata;
extern PFN_rtTextureViewCopyToBuffer rtval_next_rtTextureViewCopyToBuffer;
extern PFN_rtTextureViewExtent rtval_next_rtTextureViewExtent;
extern PFN_rtFramebufferCreate rtval_next_rtFramebufferCreate;
extern PFN_rtFramebufferDestroy rtval_next_rtFramebufferDestroy;
extern PFN_rtFramebufferColorView rtval_next_rtFramebufferColorView;
extern PFN_rtFramebufferSetColorView rtval_next_rtFramebufferSetColorView;
extern PFN_rtFramebufferDepthView rtval_next_rtFramebufferDepthView;
extern PFN_rtGraphicsProgramCreate rtval_next_rtGraphicsProgramCreate;
extern PFN_rtGraphicsProgramDestroy rtval_next_rtGraphicsProgramDestroy;
extern PFN_rtGraphicsProgramVertexLayout rtval_next_rtGraphicsProgramVertexLayout;
extern PFN_rtGraphicsProgramVertexShader rtval_next_rtGraphicsProgramVertexShader;
extern PFN_rtGraphicsProgramFragmentShader rtval_next_rtGraphicsProgramFragmentShader;
extern PFN_rtGraphicsProgramRasterState rtval_next_rtGraphicsProgramRasterState;
extern PFN_rtGraphicsProgramBlendState rtval_next_rtGraphicsProgramBlendState;
extern PFN_rtGraphicsProgramLink rtval_next_rtGraphicsProgramLink;
extern PFN_rtGraphicsProgramUniformLocation rtval_next_rtGraphicsProgramUniformLocation;
extern PFN_rtComputeProgramCreate rtval_next_rtComputeProgramCreate;
extern PFN_rtComputeProgramDestroy rtval_next_rtComputeProgramDestroy;
extern PFN_rtComputeProgramShader rtval_next_rtComputeProgramShader;
extern PFN_rtComputeProgramLink rtval_next_rtComputeProgramLink;
extern PFN_rtCmdCreate rtval_next_rtCmdCreate;
extern PFN_rtCmdDestroy rtval_next_rtCmdDestroy;
extern PFN_rtCmdBegin rtval_next_rtCmdBegin;
extern PFN_rtCmdBeginRendering rtval_next_rtCmdBeginRendering;
extern PFN_rtCmdClearColor rtval_next_rtCmdClearColor;
extern PFN_rtCmdClearDepth rtval_next_rtCmdClearDepth;
extern PFN_rtCmdClearStencil rtval_next_rtCmdClearStencil;
extern PFN_rtCmdUseGraphicsProgram rtval_next_rtCmdUseGraphicsProgram;
extern PFN_rtCmdSetScissor rtval_next_rtCmdSetScissor;
extern PFN_rtCmdUseComputeProgram rtval_next_rtCmdUseComputeProgram;
extern PFN_rtCmdUniformBuffer rtval_next_rtCmdUniformBuffer;
extern PFN_rtCmdUniformTexture rtval_next_rtCmdUniformTexture;
extern PFN_rtCmdStorageBuffer rtval_next_rtCmdStorageBuffer;
extern PFN_rtCmdStorageTexture rtval_next_rtCmdStorageTexture;
extern PFN_rtCmdComputeBarrier rtval_next_rtCmdComputeBarrier;
extern PFN_rtCmdBindVertexBuffer rtval_next_rtCmdBindVertexBuffer;
extern PFN_rtCmdDraw rtval_next_rtCmdDraw;
extern PFN_rtCmdDispatch rtval_next_rtCmdDispatch;
extern PFN_rtCmdEndRendering rtval_next_rtCmdEndRendering;
extern PFN_rtCmdEnd rtval_next_rtCmdEnd;
extern PFN_rtQueueQuery rtval_next_rtQueueQuery;
extern PFN_rtQueueWait rtval_next_rtQueueWait;
extern PFN_rtQueueSubmit rtval_next_rtQueueSubmit;
extern PFN_rtQueueFlush rtval_next_rtQueueFlush;
extern PFN_rtTimepointWait rtval_next_rtTimepointWait;
extern PFN_rtTimepointReached rtval_next_rtTimepointReached;
extern PFN_rtSwapchainCreate rtval_next_rtSwapchainCreate;
extern PFN_rtSwapchainDestroy rtval_next_rtSwapchainDestroy;
extern PFN_rtSwapchainResize rtval_next_rtSwapchainResize;
extern PFN_rtSwapchainAcquire rtval_next_rtSwapchainAcquire;
extern PFN_rtSwapchainPresent rtval_next_rtSwapchainPresent;
extern PFN_rtSwapchainBindWindowGLFW rtval_next_rtSwapchainBindWindowGLFW;
extern PFN_rtSetOutput rtval_next_rtSetOutput;

void rtval_rtInit(const char* const* features, u32 feature_count);
void rtval_rtExit(void);
enum rt_error rtval_rtError(void);
const char* rtval_rtErrorMessage(void);
void rtval_rtClearError(void);
const char* rtval_rtGetName(void);
enum rt_format_usage rtval_rtQueryFormatCapabilities(enum rt_format format);
void rtval_rtSetOutput(PFN_rtOutput output, void* user_data);

#endif
