#ifndef RTVAL_PROCS_H
#define RTVAL_PROCS_H

#define RT_NO_API_WRAPPERS
#include "rt_ext_compute.h"
#include "rt_ext_glfw.h"
#include "rt_ext_swapchain.h"
#include "rutile.h"
#include "types.h"
#undef RT_NO_API_WRAPPERS

extern PFN_rtInit rtval_next_rtInit;
extern PFN_rtExit rtval_next_rtExit;
extern PFN_rtError rtval_next_rtError;
extern PFN_rtErrorMessage rtval_next_rtErrorMessage;
extern PFN_rtClearError rtval_next_rtClearError;
extern PFN_rtGetName rtval_next_rtGetName;
extern PFN_rtQueryFormatCapabilities rtval_next_rtQueryFormatCapabilities;
extern PFN_rtBufferCreate rtval_next_rtBufferCreate;
extern PFN_rtBufferDestroy rtval_next_rtBufferDestroy;
extern PFN_rtBufferData rtval_next_rtBufferData;
extern PFN_rtBufferSubdata rtval_next_rtBufferSubdata;
extern PFN_rtBufferRead rtval_next_rtBufferRead;
extern PFN_rtBufferMap rtval_next_rtBufferMap;
extern PFN_rtBufferUnmap rtval_next_rtBufferUnmap;
extern PFN_rtTextureCreate rtval_next_rtTextureCreate;
extern PFN_rtTextureDestroy rtval_next_rtTextureDestroy;
extern PFN_rtTextureViewCreate rtval_next_rtTextureViewCreate;
extern PFN_rtTextureViewDestroy rtval_next_rtTextureViewDestroy;
extern PFN_rtTextureViewFilter rtval_next_rtTextureViewFilter;
extern PFN_rtTextureViewAddress rtval_next_rtTextureViewAddress;
extern PFN_rtTextureViewAnisotropy rtval_next_rtTextureViewAnisotropy;
extern PFN_rtTextureViewLod rtval_next_rtTextureViewLod;
extern PFN_rtTextureCopy rtval_next_rtTextureCopy;
extern PFN_rtTextureData rtval_next_rtTextureData;
extern PFN_rtTextureSubcopy rtval_next_rtTextureSubcopy;
extern PFN_rtTextureSubdata rtval_next_rtTextureSubdata;
extern PFN_rtTextureViewCopyToBuffer rtval_next_rtTextureViewCopyToBuffer;
extern PFN_rtTextureViewExtent rtval_next_rtTextureViewExtent;
extern PFN_rtFramebufferCreate rtval_next_rtFramebufferCreate;
extern PFN_rtFramebufferDestroy rtval_next_rtFramebufferDestroy;
extern PFN_rtFramebufferColorView rtval_next_rtFramebufferColorView;
extern PFN_rtFramebufferSetColorView rtval_next_rtFramebufferSetColorView;
extern PFN_rtFramebufferDepthView rtval_next_rtFramebufferDepthView;
extern PFN_rtGraphicsProgramCreate rtval_next_rtGraphicsProgramCreate;
extern PFN_rtGraphicsProgramDestroy rtval_next_rtGraphicsProgramDestroy;
extern PFN_rtGraphicsProgramVertexLayout rtval_next_rtGraphicsProgramVertexLayout;
extern PFN_rtGraphicsProgramVertexShader rtval_next_rtGraphicsProgramVertexShader;
extern PFN_rtGraphicsProgramFragmentShader rtval_next_rtGraphicsProgramFragmentShader;
extern PFN_rtGraphicsProgramRasterState rtval_next_rtGraphicsProgramRasterState;
extern PFN_rtGraphicsProgramBlendState rtval_next_rtGraphicsProgramBlendState;
extern PFN_rtGraphicsProgramLink rtval_next_rtGraphicsProgramLink;
extern PFN_rtGraphicsProgramUniformLocation rtval_next_rtGraphicsProgramUniformLocation;
extern PFN_rtComputeProgramCreate rtval_next_rtComputeProgramCreate;
extern PFN_rtComputeProgramDestroy rtval_next_rtComputeProgramDestroy;
extern PFN_rtComputeProgramShader rtval_next_rtComputeProgramShader;
extern PFN_rtComputeProgramLink rtval_next_rtComputeProgramLink;
extern PFN_rtCmdCreate rtval_next_rtCmdCreate;
extern PFN_rtCmdDestroy rtval_next_rtCmdDestroy;
extern PFN_rtCmdBegin rtval_next_rtCmdBegin;
extern PFN_rtCmdBeginRendering rtval_next_rtCmdBeginRendering;
extern PFN_rtCmdClearColor rtval_next_rtCmdClearColor;
extern PFN_rtCmdClearDepth rtval_next_rtCmdClearDepth;
extern PFN_rtCmdClearStencil rtval_next_rtCmdClearStencil;
extern PFN_rtCmdUseGraphicsProgram rtval_next_rtCmdUseGraphicsProgram;
extern PFN_rtCmdSetScissor rtval_next_rtCmdSetScissor;
extern PFN_rtCmdUseComputeProgram rtval_next_rtCmdUseComputeProgram;
extern PFN_rtCmdUniformBuffer rtval_next_rtCmdUniformBuffer;
extern PFN_rtCmdUniformTexture rtval_next_rtCmdUniformTexture;
extern PFN_rtCmdStorageBuffer rtval_next_rtCmdStorageBuffer;
extern PFN_rtCmdStorageTexture rtval_next_rtCmdStorageTexture;
extern PFN_rtCmdComputeBarrier rtval_next_rtCmdComputeBarrier;
extern PFN_rtCmdBindVertexBuffer rtval_next_rtCmdBindVertexBuffer;
extern PFN_rtCmdDraw rtval_next_rtCmdDraw;
extern PFN_rtCmdDispatch rtval_next_rtCmdDispatch;
extern PFN_rtCmdEndRendering rtval_next_rtCmdEndRendering;
extern PFN_rtCmdEnd rtval_next_rtCmdEnd;
extern PFN_rtQueueQuery rtval_next_rtQueueQuery;
extern PFN_rtQueueWait rtval_next_rtQueueWait;
extern PFN_rtQueueSubmit rtval_next_rtQueueSubmit;
extern PFN_rtQueueFlush rtval_next_rtQueueFlush;
extern PFN_rtTimepointWait rtval_next_rtTimepointWait;
extern PFN_rtTimepointReached rtval_next_rtTimepointReached;
extern PFN_rtSwapchainCreate rtval_next_rtSwapchainCreate;
extern PFN_rtSwapchainDestroy rtval_next_rtSwapchainDestroy;
extern PFN_rtSwapchainResize rtval_next_rtSwapchainResize;
extern PFN_rtSwapchainAcquire rtval_next_rtSwapchainAcquire;
extern PFN_rtSwapchainPresent rtval_next_rtSwapchainPresent;
extern PFN_rtSwapchainBindWindowGLFW rtval_next_rtSwapchainBindWindowGLFW;
extern PFN_rtSetOutput rtval_next_rtSetOutput;

void rtval_rtInit(const char* const* features, u32 feature_count);
void rtval_rtExit(void);
enum rt_error rtval_rtError(void);
const char* rtval_rtErrorMessage(void);
void rtval_rtClearError(void);
const char* rtval_rtGetName(void);
enum rt_format_usage rtval_rtQueryFormatCapabilities(enum rt_format format);
rt_buffer rtval_rtBufferCreate(void);
void rtval_rtBufferDestroy(rt_buffer buffer);
rt_timepoint rtval_rtBufferData(rt_buffer buffer, enum rt_buffer_mode mode, enum rt_buffer_usage usage, u64 size, const void* data);
rt_timepoint rtval_rtBufferSubdata(rt_buffer buffer, u64 offset, u64 size, const void* data);
void rtval_rtBufferRead(rt_buffer buffer, u64 offset, u64 size, void* data);
void* rtval_rtBufferMap(rt_buffer buffer, u64 offset, u64 size);
void rtval_rtBufferUnmap(rt_buffer buffer);
rt_texture rtval_rtTextureCreate(void);
void rtval_rtTextureDestroy(rt_texture texture);
rt_texture_view rtval_rtTextureViewCreate(rt_texture texture);
void rtval_rtTextureViewDestroy(rt_texture_view texture_view);
void rtval_rtTextureViewFilter(rt_texture_view texture_view, enum rt_filter mag_filter, enum rt_filter min_filter, enum rt_mip_filter mip_filter);
void rtval_rtTextureViewAddress(rt_texture_view texture_view, enum rt_address_mode address_u, enum rt_address_mode address_v, enum rt_address_mode address_w);
void rtval_rtTextureViewAnisotropy(rt_texture_view texture_view, u32 max_anisotropy);
void rtval_rtTextureViewLod(rt_texture_view texture_view, f32 min_lod, f32 max_lod, f32 lod_bias);
rt_timepoint rtval_rtTextureCopy(rt_queue queue, rt_texture src_texture, u32 src_mip, rt_texture dst_texture, u32 dst_mip);
rt_timepoint rtval_rtTextureData(rt_queue queue, rt_texture texture, enum rt_texture_type type, u32 mip, u32 offset_x, u32 offset_y, u32 offset_z, enum rt_format format, const void* data);
rt_timepoint rtval_rtTextureSubcopy(rt_queue queue, rt_texture src_texture, u32 src_mip, u32 src_x, u32 src_y, u32 src_z, rt_texture dst_texture, u32 dst_mip, u32 dst_x, u32 dst_y, u32 dst_z, u32 width, u32 height, u32 depth);
rt_timepoint rtval_rtTextureSubdata(rt_queue queue, rt_texture texture, u32 mip, u32 offset_x, u32 offset_y, u32 offset_z, u32 width, u32 height, u32 depth, const void* data);
rt_timepoint rtval_rtTextureViewCopyToBuffer(rt_queue queue, rt_texture_view texture_view, rt_buffer buffer);
rt_extent_3d rtval_rtTextureViewExtent(rt_texture_view texture_view);
rt_framebuffer rtval_rtFramebufferCreate(void);
void rtval_rtFramebufferDestroy(rt_framebuffer framebuffer);
rt_texture_view rtval_rtFramebufferColorView(rt_framebuffer framebuffer, u32 slot);
void rtval_rtFramebufferSetColorView(rt_framebuffer framebuffer, u32 slot, rt_texture_view view);
void rtval_rtFramebufferDepthView(rt_framebuffer framebuffer, rt_texture_view view);
rt_graphics_program rtval_rtGraphicsProgramCreate(void);
void rtval_rtGraphicsProgramDestroy(rt_graphics_program program);
void rtval_rtGraphicsProgramVertexLayout(rt_graphics_program program, const rt_vertex_layout* layout);
void rtval_rtGraphicsProgramVertexShader(rt_graphics_program program, u64 size, const void* data);
void rtval_rtGraphicsProgramFragmentShader(rt_graphics_program program, u64 size, const void* data);
void rtval_rtGraphicsProgramRasterState(rt_graphics_program program, enum rt_cull_mode cull_mode, enum rt_front_face front_face, enum rt_fill_mode fill_mode);
void rtval_rtGraphicsProgramBlendState(rt_graphics_program program, bool enabled, enum rt_blend_factor src_color, enum rt_blend_factor dst_color, enum rt_blend_op color_op, enum rt_blend_factor src_alpha, enum rt_blend_factor dst_alpha, enum rt_blend_op alpha_op);
void rtval_rtGraphicsProgramLink(rt_graphics_program program);
rt_uniform_location rtval_rtGraphicsProgramUniformLocation(rt_graphics_program program, const char* name);
rt_compute_program rtval_rtComputeProgramCreate(void);
void rtval_rtComputeProgramDestroy(rt_compute_program program);
void rtval_rtComputeProgramShader(rt_compute_program program, u64 size, const void* data);
void rtval_rtComputeProgramLink(rt_compute_program program);
rt_command_buffer rtval_rtCmdCreate(void);
void rtval_rtCmdDestroy(rt_command_buffer command_buffer);
void rtval_rtCmdBegin(rt_command_buffer command_buffer, rt_queue queue);
void rtval_rtCmdBeginRendering(rt_command_buffer command_buffer, rt_framebuffer framebuffer);
void rtval_rtCmdClearColor(rt_command_buffer command_buffer, u32 color_index, f32 r, f32 g, f32 b, f32 a);
void rtval_rtCmdClearDepth(rt_command_buffer command_buffer, f32 depth);
void rtval_rtCmdClearStencil(rt_command_buffer command_buffer, u32 stencil);
void rtval_rtCmdUseGraphicsProgram(rt_command_buffer command_buffer, rt_graphics_program program);
void rtval_rtCmdSetScissor(rt_command_buffer command_buffer, u32 x, u32 y, u32 width, u32 height);
void rtval_rtCmdUseComputeProgram(rt_command_buffer command_buffer, rt_compute_program program);
void rtval_rtCmdUniformBuffer(rt_command_buffer command_buffer, rt_uniform_location location, rt_buffer buffer, u64 offset, u64 size);
void rtval_rtCmdUniformTexture(rt_command_buffer command_buffer, rt_uniform_location location, rt_texture_view texture_view);
void rtval_rtCmdStorageBuffer(rt_command_buffer command_buffer, u32 binding, rt_buffer buffer, u64 offset, u64 size);
void rtval_rtCmdStorageTexture(rt_command_buffer command_buffer, u32 binding, rt_texture_view texture_view);
void rtval_rtCmdComputeBarrier(rt_command_buffer command_buffer);
void rtval_rtCmdBindVertexBuffer(rt_command_buffer command_buffer, rt_buffer buffer, u64 offset);
void rtval_rtCmdDraw(rt_command_buffer command_buffer, u32 vertex_count, u32 first_vertex);
void rtval_rtCmdDispatch(rt_command_buffer command_buffer, u32 group_count_x, u32 group_count_y, u32 group_count_z);
void rtval_rtCmdEndRendering(rt_command_buffer command_buffer);
void rtval_rtCmdEnd(rt_command_buffer command_buffer);
void rtval_command_buffer_reset_tracking(void);
bool rtval_command_buffer_ready_for_submit(rt_command_buffer command_buffer, rt_queue queue);
rt_queue rtval_rtQueueQuery(enum rt_queue_capability capability);
void rtval_rtQueueWait(rt_queue queue, rt_timepoint timepoint);
rt_timepoint rtval_rtQueueSubmit(rt_queue queue, rt_command_buffer command_buffer);
rt_timepoint rtval_rtQueueFlush(rt_queue queue);
void rtval_rtTimepointWait(rt_timepoint timepoint);
bool rtval_rtTimepointReached(rt_timepoint timepoint);
rt_swapchain rtval_rtSwapchainCreate(void);
void rtval_rtSwapchainDestroy(rt_swapchain swapchain);
void rtval_rtSwapchainResize(rt_swapchain swapchain, u32 width, u32 height);
rt_swapchain_acquire_result rtval_rtSwapchainAcquire(rt_swapchain swapchain);
void rtval_rtSwapchainPresent(rt_swapchain swapchain, rt_timepoint rendered);
void rtval_rtSwapchainBindWindowGLFW(rt_swapchain swapchain, GLFWwindow* window);
void rtval_rtSetOutput(PFN_rtOutput output, void* user_data);

#endif
